#!/bin/bash
#
#	written up by Jan Engelhardt, 2008
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the WTF Public License version 2 or
#	(at your option) any later version.
#

current_branch=$(pcregrep -o '(?<=^ref: refs/heads/).+$' .git/HEAD);
if [[ -z "$current_branch" ]]; then
	echo You do not seem to be on a branch >&2;
	exit 1;
fi;

remote_name="${1%/*}";
remote_branch="${1#*/}";

git config "branch.$current_branch.remote" "$remote_name";
git config "branch.$current_branch.merge" "$remote_branch";
