#!/bin/bash
# written up by Jan Engelhardt, 2008
# Public Domain

if [[ -z "$1" ]]; then
	echo "Need a branch name";
	exit 1;
fi;
git symbolic-ref HEAD "refs/heads/$1";
rm -f .git/index;
git clean -df;
