.TH parkverbot 8 "2011-12-28" "hxtools" "hxtools"
.SH Name
parkverbot \(em daemon to inhibit hard disk head parking
.SH Synopsis
\fBparkverbot\fP [\fB\-r\fP \fIkbytes\fP] [\fB\-t\fP \fIsecs\fP]
\fIdevice\fP...
.SH Introduction
.PP
Dear Manufacturers of spinning magnetic hard disks! The periodic automatic head
unloading, measurable by the S.M.A.R.T. attribute no. 225 "Load_Cycle_Count",
is a real bother: latency on wake-up, and it cannot be turned off reliably.
hdparm -B is most of the time ineffective, not to mention that hdparm does not
work with SCSI/SAS disks, and using a DOS utility disk just is not realistic.
It is believed that the head unloading leads to a shorter lifetime, and while
you may refute that, it is not hard to believe that you want us to buy new
disks sooner than later. In short, you suck. And while you do, this little
utility tries to counter-effect this.
.SH Description
.PP
The "parkverbot" daemon will periodically read data from a random location on disk in an
effort to reset the inactivity timer in the hardware and so prevent the dreaded
head unloading mis-feature of today's disks.
.PP
parkverbot obsoletes the earlier "thkd" package.
.PP
The name stems from German and indicates parking prohibition (you probably
already guessed that), or more commonly known as a "no parking" zone.
.SH Options
.PP
\fB\-r\fP \fIsize\fP
The guard window size (defaults to 16 MB). When requesting a block off the
disk, the hardware might choose to cache more parts, as it will have to hover
and wait over a particular track for the desired sector. If the next random
block we choose happens to be already cached because of that, the head unload
timer will not be reset. To avoid this, if the new random location falls within
\fIsize\fP kilobytes, we shuffle out a new location and retry.
.PP
\fB\-t\fP \fIsecs\fP
The interval in which to request blocks (defaults to 4 sec).
