.TH printcaps 8 "2011-12-14" "hxtools" "hxtools"
.SH Name
.PP
printcaps \(em print capabilities of processes in human-readable fashion
.SH Syntax
.PP
\fBprintcaps\fP [\fIpid\fP...]
.SH Description
.PP
\fBprintcaps\fP outputs the capability sets of one or more processes in a
human-readable tabular fashion. PIDs may be specified to get the sets of
specific processes; if none is given, the current process (i.e. printcaps
itself) will be inspected.
