.TH sysinfo 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
sysinfo \(em print IRC-style system information banner
.\" not just for bragging - can also be useful in bug reports
.SH Syntax
.PP
\fBsysinfo\fP
.SH Description
.PP
Prints out an IRC-style machine info, like:
.PP
[seven] Linux 3.4.4-jng6-default x86_64 | 8-thr Intel(R) Core(TM) i7-2600 CPU
3401MHz | Load: 0.51 Tasks: 461 | Mem: 2672/32155MB | Disk: 656/2791GB | Gfx:
Intel Corporation 2nd Generation Core Processor Family Integrated Graphics
Controller @ 1280x1024
.PP
The load number is the EWMA over the last 60 seconds. The values shown for
memory and disk are the used amount and the total amount (NOT the free amount
and the total amount). The used memory value may theoretically exceed that of
the available memory, which is the case when memory is in general already full
\fBand\fP tmpfs files have been moved to swap (i.e. you are approaching more
trouble).
.PP
The @\fIxres\fPx\fIyres\fP is only available if $DISPLAY is set and valid.
\fIxres\fP and \fIyres\fP will be the dimensions of the \fBvirtual\fP size, not
the resolution of any particular monitor.
.SH See also
.PP
\fBhxtools\fP(7)
