.TH vfontas 1 "2003-03-08" "hxtools" "hxtools"
.SH Name
.PP
vfontas \(em VGA font file assembler
.SH Syntax
.PP
\fBvfontas\fP [\fB\-EGW\fP] [\fB\-D\fP \fIdirectory\fP] [\fB\-c|\-\-create\fP]
[\fB\-f\fP \fIfile\fP] [\fB\-x|\-\-extract\fP]
.SH Description
.PP
VFontAS (VGA font file assembler). This small utility works on 8x16x256 bit
raw font files (FNT). It can extract the chars from a FNT, that is, convert
them to a textual bitmap, and merge them back; mainly to create fonts.
.SH Syntax
.TP
\fB\-D\fP \fIdirectory\fP
Directory to read/write glyphs from/to.
.TP
\fB\-E\fP
Create an empty font file.
.TP
\fB\-G\fP
Convert a raw 8x16 FNT file from stdin to a 9x16 PSF2 suitable for fbdev, while
extending the 8th column to the 9th column like the PC VGA BIOS mode 01h does.
.TP
\fB\-W\fP
Convert a raw 8x16 FNT file from stdin to a 16x16 PSF2, mimicing 40x25 text
mode on a 80x25 display.
.TP
\fB\-c\fP, \fB\-\-create\fP
Create a new FNT file by readnig all glyphs from the directory specified by
\-D.
.TP
\fB\-f\fP \fIfile\fP
Read/write from/to the VGA font stored in \fIfile\fP.
.TP
\fB\-x\fP, \fB\-\-extract\fP
Extract the VGA font file's glyphs into the directory specified by \-D.
.PP
Only one of \-E, \-c or \-x can be specified.
.SH See also
.PP
\fBhxtools\fP(7)
