#!/usr/bin/perl

use strict;
# as per include/linux/asm-generic/param.h
our $CPS = 100;
my $x;
while (<>) {
	my @args = split(/\s+/, $_);
	print "pid_nr: ", shift(@args), "\n";
	print "tcomm: ", shift(@args), "\n";
	print "state: ", shift(@args), "\n";
	print "ppid: ", shift(@args), "\n";
	print "pgid: ", shift(@args), "\n";
	print "sid: ", shift(@args), "\n";
	print "tty_nr: ", shift(@args), "\n";
	print "tty_pgrp: ", shift(@args), "\n";
	$x = shift @args;
	printf "task_flags: %d / 0x%x\n", $x, $x;
	print "min_flt: ", shift(@args), "\n";
	print "cmin_flt: ", shift(@args), "\n";
	print "max_flt: ", shift(@args), "\n";
	print "cmax_flt: ", shift(@args), "\n";
	my $x = shift @args;
	printf "utime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	my $x = shift @args;
	printf "stime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	my $x = shift @args;
	printf "cutime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	my $x = shift @args;
	printf "cstime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	print "priority: ", shift(@args), "\n";
	print "nice: ", shift(@args), "\n";
	print "num_threads: ", shift(@args), "\n";
	print "always-zero: ", shift(@args), "\n";
	print "start_time: ", shift(@args), "\n";
	print "vsize: ", shift(@args), "\n";
	print "get_mm_rss: ", shift(@args), "\n";
	$x = shift @args;
	printf "rsslim: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "mm_start_code: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "mm_end_code: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "mm_start_stack: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "esp: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "eip: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "obsolete-pending-signals: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "obsolete-blocked-signals: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "obsolete-sigign: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "obsolete-sigcatch: %llu / 0x%llx\n", $x, $x;
	$x = shift @args;
	printf "wchan: %llu / 0x%llx\n", $x, $x;
	print "always-zero: ", shift(@args), "\n";
	print "always-zero: ", shift(@args), "\n";
	print "task_exit_signal: ", shift(@args), "\n";
	print "task_cpu: ", shift(@args), "\n";
	print "task_rt_priority: ", shift(@args), "\n";
	print "task_policy: ", shift(@args), "\n";
	print "delayacct_blkio_ticks: ", shift(@args), "\n";
	$x = shift @args;
	printf "gtime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	$x = shift @args;
	printf "cgtime: %lu clocks (= %ld clocks) (= %f s)\n", $x, $x, $x/$CPS;
	print "UNPARSED: ", join(" ", @args), "\n";
}
